using System;
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.InputSystem;
using LastGod.Core;
using LastGod.Input;

namespace LastGod.Player
{
    // ─── State enum ───────────────────────────────────────────────────────────
    /// <summary>
    /// All mutually exclusive player states.
    /// Only one can be active at a time — no boolean soup.
    /// </summary>
    public enum PlayerState
    {
        Idle,
        Run,
        Jump,
        Attack,
        Hurt,
        Dead
    }

    // ─── PlayerController ─────────────────────────────────────────────────────
    /// <summary>
    /// Root player brain. Reads input, drives the state machine, moves the body.
    ///
    /// Required components (auto-added via [RequireComponent]):
    ///   Rigidbody2D   — Dynamic, Freeze Rotation Z
    ///   CapsuleCollider2D
    ///   Health        — HP pool / damage reception
    ///
    /// Input asset: PlayerInputActions (generated C# class).
    /// Create it via: Assets/Settings/Input/PlayerInputActions.inputactions
    /// then enable "Generate C# Class" in its inspector.
    /// </summary>
    [RequireComponent(typeof(Rigidbody2D))]
    [RequireComponent(typeof(CapsuleCollider2D))]
    [RequireComponent(typeof(Health))]
    public class PlayerController : MonoBehaviour
    {
        // ─── Inspector ────────────────────────────────────────────────────────
        [Header("Movement")]
        [Tooltip("Horizontal run speed in Unity units/sec. At PPU=16, ~6 = GBA feel.")]
        [SerializeField] private float moveSpeed = 6f;

        [Header("Jump")]
        [SerializeField] private float jumpForce = 14f;
        [Tooltip("Extra gravity when the player releases Jump early (variable jump height).")]
        [SerializeField] private float fallMultiplier = 3f;
        [Tooltip("How thick the ground-check overlap box is.")]
        [SerializeField] private float groundCheckDistance = 0.05f;
        [SerializeField] private LayerMask groundLayer;

        [Header("Dash")]
        [SerializeField] private float dashSpeed = 18f;
        [SerializeField] private float dashDuration = 0.15f;   // seconds the dash lasts
        [SerializeField] private float dashCooldown = 0.8f;    // seconds before can dash again
        [SerializeField] private float dashInvincibilityWindow = 0.2f; // seconds of i-frames

        [Header("Events")]
        /// <summary>
        /// Fired every time the state machine transitions.
        /// Subscribe from animation / VFX / audio controllers.
        /// Args: (previous state, new state)
        /// </summary>
        public UnityEvent<PlayerState, PlayerState> OnStateChanged = new();

        // ─── Components ───────────────────────────────────────────────────────
        private Rigidbody2D _rb;
        private CapsuleCollider2D _col;
        private Health _health;

        // ─── Input ────────────────────────────────────────────────────────────
        // Generated by Input System from the .inputactions asset.
        // If the class is missing, open the asset and enable "Generate C# Class".
        private PlayerInputActions _input;
        private Vector2 _moveInput;
        private bool _jumpPressed;
        private bool _attackPressed;
        private bool _dashPressed;

        // ─── State machine ────────────────────────────────────────────────────
        private PlayerState _state = PlayerState.Idle;

        /// <summary>Current player state (read-only from outside).</summary>
        public PlayerState State => _state;

        // ─── Runtime flags ────────────────────────────────────────────────────
        private bool _isGrounded;
        private bool _facingRight = true;

        // Dash
        private bool _isDashing;
        private float _dashTimer;
        private float _dashCooldownTimer;
        private bool _isDashInvincible;
        private float _dashInvincibilityTimer;

        // Hurt
        private float _hurtLockTimer;   // brief window player can't act after being hit
        private const float HurtLockDuration = 0.4f;

        // ─── Unity lifecycle ──────────────────────────────────────────────────
        private void Awake()
        {
            _rb     = GetComponent<Rigidbody2D>();
            _col    = GetComponent<CapsuleCollider2D>();
            _health = GetComponent<Health>();

            // Rigidbody setup enforced in code as a safety net
            // (Inspector settings are the source of truth but this guards against prefab resets)
            _rb.gravityScale   = 3f;
            _rb.freezeRotation = true;
            _rb.interpolation  = RigidbodyInterpolation2D.Interpolate;
            _rb.collisionDetectionMode = CollisionDetectionMode2D.Continuous;

            // Wire Health events
            _health.OnDamaged.AddListener(OnDamaged);
            _health.OnDeath.AddListener(OnDeath);

            // Input
            _input = new PlayerInputActions();
        }

        private void OnEnable()
        {
            _input.Player.Enable();

            // Cache actions for readability
            _input.Player.Move.performed   += ctx => _moveInput   = ctx.ReadValue<Vector2>();
            _input.Player.Move.canceled    += ctx => _moveInput   = Vector2.zero;
            _input.Player.Jump.performed   += ctx => _jumpPressed  = true;
            _input.Player.Attack.performed += ctx => _attackPressed = true;
            _input.Player.Dash.performed   += ctx => _dashPressed  = true;
        }

        private void OnDisable()
        {
            _input.Player.Disable();
        }

        private void Update()
        {
            TickTimers();
            CheckGround();
            ProcessInput();

            // Consume single-frame flags after processing
            _jumpPressed   = false;
            _attackPressed = false;
            _dashPressed   = false;
        }

        private void FixedUpdate()
        {
            ApplyMovement();
            ApplyFallMultiplier();
        }

        // ─── Ground detection ─────────────────────────────────────────────────
        private void CheckGround()
        {
            // Cast a small box just below the collider feet.
            Bounds b  = _col.bounds;
            Vector2 origin = new(b.center.x, b.min.y);
            Vector2 size   = new(b.size.x * 0.9f, groundCheckDistance);
            _isGrounded = Physics2D.OverlapBox(origin, size, 0f, groundLayer);
        }

        // ─── State machine ────────────────────────────────────────────────────
        private void SetState(PlayerState next)
        {
            if (_state == next) return;

            PlayerState prev = _state;
            _state = next;
            OnStateChanged.Invoke(prev, next);
        }

        // ─── Input → state transitions ────────────────────────────────────────
        private void ProcessInput()
        {
            // Dead state: ignore all input
            if (_state == PlayerState.Dead) return;

            // Hurt: locked briefly
            if (_state == PlayerState.Hurt)
            {
                if (_hurtLockTimer <= 0f)
                    SetState(PlayerState.Idle);
                return;
            }

            // Dashing: committed until timer expires
            if (_isDashing)
            {
                if (_dashTimer <= 0f)
                    EndDash();
                return;
            }

            // --- Dash (highest priority after damage) ---
            if (_dashPressed && _dashCooldownTimer <= 0f)
            {
                StartDash();
                return;
            }

            // --- Attack ---
            if (_attackPressed && _state != PlayerState.Attack)
            {
                SetState(PlayerState.Attack);
                // Placeholder — real hitbox spawning comes in Prompt 2
                Debug.Log("[Player] Attack triggered — hitbox goes here (Prompt 2)");
                // After a future animation event, call EndAttack()
                // For now return to movement state next frame:
                Invoke(nameof(EndAttack), 0.3f);
                return;
            }

            // --- Jump ---
            if (_jumpPressed && _isGrounded)
            {
                SetState(PlayerState.Jump);
                _rb.linearVelocity = new Vector2(_rb.linearVelocity.x, jumpForce);
                return;
            }

            // --- Run / Idle ---
            if (_isGrounded)
            {
                SetState(Mathf.Abs(_moveInput.x) > 0.01f ? PlayerState.Run : PlayerState.Idle);
            }
            else
            {
                // Airborne but not jump-initiated (e.g. walked off a ledge)
                if (_state != PlayerState.Jump)
                    SetState(PlayerState.Jump);
            }
        }

        // ─── Movement ─────────────────────────────────────────────────────────
        private void ApplyMovement()
        {
            if (_state == PlayerState.Dead) return;

            if (_isDashing)
            {
                // Horizontal dash: override velocity entirely
                float dir = _facingRight ? 1f : -1f;
                _rb.linearVelocity = new Vector2(dir * dashSpeed, 0f);
                return;
            }

            if (_state == PlayerState.Hurt) return; // knockback handled by Health

            float xVel = _moveInput.x * moveSpeed;
            _rb.linearVelocity = new Vector2(xVel, _rb.linearVelocity.y);

            // Flip sprite direction
            if (_moveInput.x > 0.01f && !_facingRight)   Flip();
            if (_moveInput.x < -0.01f && _facingRight)   Flip();
        }

        /// <summary>
        /// Adds extra downward gravity when falling or when Jump is released early.
        /// Makes jumps feel snappy rather than floaty.
        /// </summary>
        private void ApplyFallMultiplier()
        {
            if (_isDashing) return;

            if (_rb.linearVelocity.y < 0f)
            {
                // Falling — apply fall multiplier
                _rb.linearVelocity += Vector2.up * Physics2D.gravity.y
                    * (fallMultiplier - 1f) * Time.fixedDeltaTime;
            }
        }

        // ─── Dash ─────────────────────────────────────────────────────────────
        private void StartDash()
        {
            _isDashing            = true;
            _dashTimer            = dashDuration;
            _dashCooldownTimer    = dashCooldown;
            _isDashInvincible     = true;
            _dashInvincibilityTimer = dashInvincibilityWindow;

            // Kill vertical momentum so dash is always horizontal
            _rb.linearVelocity = Vector2.zero;
            _rb.gravityScale   = 0f;

            SetState(PlayerState.Jump); // Reuse Jump state visually until Prompt 2 adds Dash anim
        }

        private void EndDash()
        {
            _isDashing       = false;
            _rb.gravityScale = 3f;
        }

        // ─── Attack cleanup ───────────────────────────────────────────────────
        private void EndAttack()
        {
            if (_state == PlayerState.Attack)
                SetState(_isGrounded ? PlayerState.Idle : PlayerState.Jump);
        }

        // ─── Timers ───────────────────────────────────────────────────────────
        private void TickTimers()
        {
            float dt = Time.deltaTime;

            if (_dashTimer            > 0f) _dashTimer            -= dt;
            if (_dashCooldownTimer    > 0f) _dashCooldownTimer    -= dt;
            if (_hurtLockTimer        > 0f) _hurtLockTimer        -= dt;

            if (_dashInvincibilityTimer > 0f)
            {
                _dashInvincibilityTimer -= dt;
                if (_dashInvincibilityTimer <= 0f)
                    _isDashInvincible = false;
            }
        }

        // ─── Hurt / Death callbacks ───────────────────────────────────────────
        private void OnDamaged(int remainingHP)
        {
            if (_isDashInvincible) return; // i-frames during dash

            SetState(PlayerState.Hurt);
            _hurtLockTimer = HurtLockDuration;
        }

        private void OnDeath()
        {
            SetState(PlayerState.Dead);
            _rb.linearVelocity = Vector2.zero;
            _rb.simulated      = false; // Freeze physics on death
            Debug.Log("[Player] Player died.");
        }

        // ─── Helpers ──────────────────────────────────────────────────────────
        private void Flip()
        {
            _facingRight = !_facingRight;
            Vector3 s = transform.localScale;
            s.x = -s.x;
            transform.localScale = s;
        }

        /// <summary>
        /// Whether the player is currently in the dash i-frame window.
        /// Useful for enemy AI to skip damage calls.
        /// </summary>
        public bool IsInvincible => _isDashInvincible;

        // ─── Gizmos ───────────────────────────────────────────────────────────
        private void OnDrawGizmosSelected()
        {
            if (_col == null) _col = GetComponent<CapsuleCollider2D>();
            if (_col == null) return;

            // Visualise ground-check box
            Bounds b      = _col.bounds;
            Vector3 origin = new(b.center.x, b.min.y, 0f);
            Vector3 size   = new(b.size.x * 0.9f, groundCheckDistance, 0f);

            Gizmos.color = _isGrounded ? Color.green : Color.red;
            Gizmos.DrawWireCube(origin, size);
        }
    }
}
